CREATE DATABASE IF NOT EXISTS `chaupar`;

USE `chaupar`;

CREATE TABLE IF NOT EXISTS `users` (
    `uid` INT(10) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(64) NULL DEFAULT NULL,
    `pass` VARCHAR(64) NULL DEFAULT NULL,
    `token` VARCHAR(16) NULL DEFAULT NULL,
    `created` DATE NULL DEFAULT NULL,
    PRIMARY KEY (`uid`)
);
